M48
; DRILL file {KiCad 8.0.1} date 2024-07-15T00:54:38+0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-15T00:54:38+06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X176.395Y-67.86
X176.395Y-73.64
T2
X116.25Y-54.0
X116.5Y-88.5
X168.75Y-54.0
X169.0Y-88.5
M30
